name: 'Download artifact'
description: 'Downloads and unzips dependencies artifact created at install job'
inputs:
  WORKING_DIR:
    description: 'Working directory, if the project files is not in the root'
    required: false
    default: '.'
runs:
  using: "composite"
  steps:
    - name: Download artifact of dependencies
      uses: actions/download-artifact@v3
      with:
        name: node_modules.tgz
        path: ${{ inputs.WORKING_DIR }}
    - name: Show directory
      run: |
        pwd && ls -la
        ls -la ${{ inputs.WORKING_DIR }} || true
      shell: bash
    - name: Unzip artifact of dependencies
      run: cd ${{ inputs.WORKING_DIR }} && tar -xzf node_modules.tgz
      shell: bash
    - name: Show directory
      run: |
        pwd && ls -la
        ls -la ${{ inputs.WORKING_DIR }} || true
      shell: bash