name: 'Install dependencies with yarn/nodejs'
description: 'Install necessary dependencies'
inputs:
  NODE_VERSION:
    description: "Node version to be set up"
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup node
      uses: Lattice-Trade/membrane-github-template-actions/composite-actions/yarn/setup-node.v1@main
      with:
        NODE_VERSION: ${{ inputs.NODE_VERSION }}
    - name: Install dependencies (yarn install)
      run: yarn install --frozen-lockfile
      shell: bash
    - name: Zip and upload dependencies artifact
      uses: Lattice-Trade/membrane-github-template-actions/composite-actions/git/upload-artifact.v1@main