name: 'Upload artifact'
description: 'Zips and uploads dependencies artifact'
inputs:
  WORKING_DIR:
    description: 'Working directory, if the project files is not in the root'
    required: false
    default: '.'
runs:
  using: "composite"
  steps:
    - name: Zip artifact of dependencies
      run: tar -czf node_modules.tgz  ${{ inputs.WORKING_DIR }}/node_modules
      shell: bash
    - name: Upload artifact of dependencies
      uses: actions/upload-artifact@v3
      with:
        name: node_modules.tgz
        path: node_modules.tgz
        retention-days: 2