name: 'Run build script'
description: 'Build the code'
inputs:
  NODE_VERSION:
    required: true
    description: "Node version to use"
  NPM_REGISTRY:
    description: "Hostname of NPM registry to setup"
    required: false
    default: "registry.npmjs.org"
  NPM_SCOPE:
    description: "Account owner to use as GitHub Packages scope"
    required: false
  USE_PAT:
    description: For old repos that used Personal Access tokens they should pass a TRUE. New repos will use $GITHUB_TOKEN.
    required: false
    default: "false"
  IS_RELEASE_CANDIDATE:
    description: If this a release candidate package, it will be published with an affix in NPM.
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Setup node
      uses: Lattice-Trade/membrane-github-template-actions/composite-actions/yarn/setup-node.v1@main
      with:
        NODE_VERSION: ${{ inputs.NODE_VERSION }}
        NPM_REGISTRY: ${{ inputs.NPM_REGISTRY }}
        NPM_SCOPE: ${{ inputs.NPM_SCOPE }}
    - name: Download and unzip dependencies artifact
      uses: Lattice-Trade/membrane-github-template-actions/composite-actions/git/download-artifact.v1@main
    - name: Build code
      run: yarn run build
      shell: bash
    - name: Set the right publish token (PAT or GITHUB_TOKEN)
      if: ${{ inputs.NPM_REGISTRY == 'npm.pkg.github.com' }}
      id: token
      uses: Lattice-Trade/membrane-github-template-actions/composite-actions/npm/set-publish-token.v1@main
      with:
        USE_PAT: ${{ inputs.USE_PAT }}
        NPM_TOKEN_PUBLISH: ${{ env.NPM_TOKEN_PUBLISH }}
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
    - name: Publish release candidate package to GitHub Package Registry
      # This job only runs when we try to publish new SDKs as we set our own github registry instead of npm public registry
      if: ${{ inputs.IS_RELEASE_CANDIDATE == 'true' && inputs.NPM_REGISTRY == 'npm.pkg.github.com' }}
      run: |
        yarn version --new-version $(jq -r .version package.json)-rc-$(echo ${GITHUB_SHA} | cut -c1-7) --no-git-tag-version
        cp package.json dist/
        cp README.md dist/ || true
        npm publish dist --tag beta
      env:
        NPM_TOKEN: ${{ steps.token.outputs.PUBLISH_TOKEN }}
      shell: bash
    - name: Publish stable package to GitHub Package Registry
      # This job only runs when we try to publish new SDKs as we set our own github registry instead of npm public registry
      if: ${{ inputs.IS_RELEASE_CANDIDATE == 'false' && inputs.NPM_REGISTRY == 'npm.pkg.github.com' }}
      run: |
        cp package.json dist/
        cp README.md dist/ || true
        npm publish dist
      env:
        NPM_TOKEN: ${{ steps.token.outputs.PUBLISH_TOKEN }}
      shell: bash