name: '📦 Test codebase'

on: 
  workflow_call:
    inputs:
      NODE_VERSION:
        required: true
        type: string
      HAS_UNIT_TEST:
        required: true
        type: boolean
      NPM_REGISTRY:
        description: "Hostname of NPM registry to setup"
        required: false
        type: string
        default: registry.npmjs.org
      NPM_SCOPE:
        description: "Account owner to use as GitHub Packages scope"
        type: string
        required: false
      WORKING_DIR:
        description: 'Working directory, if the project files is not in the root'
        required: false
        type: string
        default: '.'
        
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIR }}
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN_RO }}
    steps:
      - name: Check if codebase tests are difined within package.json
        uses: Lattice-Trade/membrane-public-github-actions/composite-actions/npm/check-tests.v1@main
        id: check-tests
      - name: Setup node
        uses: Lattice-Trade/membrane-public-github-actions/composite-actions/npm/setup-node.v1@main
        with:
          NODE_VERSION: ${{ inputs.NODE_VERSION }}
          WORKING_DIR: ${{ inputs.WORKING_DIR }}
      - name: Download and unzip dependencies artifact
        uses: Lattice-Trade/membrane-public-github-actions/composite-actions/git/download-artifact.v1@main
        with:
          WORKING_DIR: ${{ inputs.WORKING_DIR }}
      - name: Run unit tests
        if: inputs.HAS_UNIT_TEST
        run: npm test
      # - name: Run unit tests
      #   if: ${{ steps.check-tests.outputs.HAS_UNIT_TEST == 'true' }}
      #   run: npm run test