name: '📦 Install application dependencies'

on: 
  workflow_call:
    inputs:
      NODE_VERSION:
        required: true
        type: string
      NPM_REGISTRY:
        description: "Hostname of NPM registry to setup"
        required: false
        type: string
        default: registry.npmjs.org
      NPM_SCOPE:
        description: "Account owner to use as GitHub Packages scope"
        type: string
        required: false
      WORKING_DIR:
        description: 'Working directory, if the project files is not in the root'
        required: false
        type: string
        default: '.'
        
jobs:
  install:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIR }}
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN_RO }}
    steps:
      - name: Setup node
        uses: Lattice-Trade/membrane-github-template-actions/composite-actions/npm/setup-node.v1@main
        with:
          NODE_VERSION: ${{ inputs.NODE_VERSION }}
          WORKING_DIR: ${{ inputs.WORKING_DIR }}
      - name: Install dependencies (npm ci)
        run: npm ci
        shell: bash
      - name: Zip and upload dependencies artifact
        uses: Lattice-Trade/membrane-github-template-actions/composite-actions/git/upload-artifact.v1@main
        with:
          WORKING_DIR: ${{ inputs.WORKING_DIR }}