name: Build & Publish to Registry

on:
  workflow_call:
    inputs:
      HAS_UNIT_TEST:
        required: false
        type: boolean
        default: false
      NODE_VERSION:
        required: true
        type: string
      USE_PAT:
        description: For repos that already published using Personal Access tokens, they should input a true. New repos will use $GITHUB_TOKEN.
        required: false
        type: boolean
        default: false
      IS_RELEASE_CANDIDATE:
        description: If this a release candidate package, it will be published with an affix in NPM.
        required: false
        type: boolean
        default: false
      USE_JS:
        description: If the project uses JS or TS, the publish command changes.
        required: false
        type: boolean
        default: false

permissions:
  contents: write
  packages: write
  repository-projects: write

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN_RO }}
  NODE_VERSION: ${{ inputs.NODE_VERSION }}
  NPM_TOKEN_PUBLISH: ${{ secrets.NPM_TOKEN_PUBLISH }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  install:
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        uses: Lattice-Trade/membrane-github-template-actions/composite-actions/yarn/install.v1@main
        with:
          NODE_VERSION: ${{ env.NODE_VERSION }}

  lint:
    needs: install
    if: always() && needs.install.result == 'success'
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        uses: Lattice-Trade/membrane-github-template-actions/composite-actions/yarn/lint.v1@main
        with:
          NODE_VERSION: ${{ env.NODE_VERSION }}

  test:
    needs: install
    if: always() && needs.install.result == 'success' && inputs.HAS_UNIT_TEST
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        uses: Lattice-Trade/membrane-github-template-actions/composite-actions/yarn/lint.v1@main
        with:
          NODE_VERSION: ${{ env.NODE_VERSION }}

  build:
    needs: [test, lint]
    if: |
      always() &&
      needs.lint.result == 'success' &&
      (needs.test.result == 'success' || needs.test.result == 'skipped')
    runs-on: ubuntu-22.04
    steps:
      - name: Build application
        uses: Lattice-Trade/membrane-github-template-actions/composite-actions/yarn/build.v1@main
        with:
          NODE_VERSION: ${{ env.NODE_VERSION }}
          NPM_REGISTRY: npm.pkg.github.com
          NPM_SCOPE: "@${{ github.repository_owner }}"
          USE_PAT: ${{ inputs.USE_PAT }}
          IS_RELEASE_CANDIDATE: ${{ inputs.IS_RELEASE_CANDIDATE }}
          USE_JS: ${{ inputs.USE_JS }}